name: CI
on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        arch:
          - amd64
          # - arm64
    steps:
      - uses: actions/checkout@v2
      - uses: esphome/build-action@v1
        id: esphome-build
        with:
          yaml_file: FunHouse.yaml
      - uses: actions/upload-artifact@v2
        with:
          name: FunHouse-${{ steps.esphome-build.outputs.name }}
          path: ${{ steps.esphome-build.outputs.name }}
